import React, { useState } from "react";
import { ProjectSession, AgentTask } from "../types";
import confetti from "canvas-confetti";
import {
  Bot,
  Sparkles,
  Download,
  Copy,
  Check,
  RefreshCw,
  Code2,
  CheckCircle2,
  ListOrdered,
  ChevronDown,
  ChevronUp,
  Kanban,
  ArrowRight,
  X,
} from "lucide-react";

interface Step3AgentTasksProps {
  session: ProjectSession;
  onUpdateSession: (updated: Partial<ProjectSession>) => void;
}

export const Step3AgentTasks: React.FC<Step3AgentTasksProps> = ({ session, onUpdateSession }) => {
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedTaskId, setCopiedTaskId] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);
  const [expandedTasks, setExpandedTasks] = useState<Record<string, boolean>>({});
  const [viewMode, setViewMode] = useState<"kanban" | "list">("kanban");
  const [selectedTaskForModal, setSelectedTaskForModal] = useState<AgentTask | null>(null);

  const tasks = session.tasks || [];

  const handleGenerateTasks = async () => {
    setLoading(true);
    setErrorMessage(null);

    try {
      const res = await fetch("/api/generate-tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: session.input.title || session.title || "Aplikasi AI",
          plan: session.plan,
          prd: session.prd,
          llmConfig: session.llmConfig,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Gagal membuat Agent Tasks.");

      const generatedTasks: AgentTask[] = (data.tasks || []).map((t: AgentTask) => ({
        ...t,
        status: t.status || "todo",
      }));

      onUpdateSession({
        tasks: generatedTasks,
      });

      // Expand all by default
      const initialExpanded: Record<string, boolean> = {};
      generatedTasks.forEach((t) => (initialExpanded[t.id] = true));
      setExpandedTasks(initialExpanded);

      // Trigger celebratory confetti
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
      });
    } catch (err: any) {
      setErrorMessage(err.message || "Terjadi kesalahan saat membuat Agent Tasks.");
    } finally {
      setLoading(false);
    }
  };

  const handleTaskStatusChange = (taskId: string, newStatus: "todo" | "in_progress" | "done") => {
    const updated = tasks.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t));
    onUpdateSession({ tasks: updated });
    if (selectedTaskForModal && selectedTaskForModal.id === taskId) {
      setSelectedTaskForModal({ ...selectedTaskForModal, status: newStatus });
    }
  };

  const toggleExpand = (id: string) => {
    setExpandedTasks((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleCopyTaskPrompt = (task: AgentTask) => {
    const text = `PROMPT AI AGENT [${task.id}] - ${task.title}\n` +
      `File Target: ${(task.targetFiles || []).join(", ")}\n` +
      `\nInstruksi:\n${task.promptInstructions}\n` +
      `\nLangkah Verifikasi:\n${task.verificationSteps}`;

    navigator.clipboard.writeText(text);
    setCopiedTaskId(task.id);
    setTimeout(() => setCopiedTaskId(null), 2000);
  };

  const buildBundledMarkdown = (): string => {
    const titleStr = session.input.title || session.title || "PROYEK AI";
    let md = `# AI AGENT EXECUTION TASKS: ${titleStr.toUpperCase()}\n\n`;
    md += `> Generated by The Architech on ${new Date().toLocaleDateString()}\n`;
    md += `> Target System: AI Coding Agent (Cursor, Antigravity Agent, Gemini, Claude Code)\n\n`;
    md += `## RULES FOR AI AGENT EXECUTION\n`;
    md += `1. Jalankan tugas berurutan berdasarkan ID Task (TASK-01, TASK-02, ...).\n`;
    md += `2. Selalu baca file target sebelum mengedit untuk menghindari konflik.\n`;
    md += `3. Lakukan verifikasi di akhir setiap task sebelum melanjutkan.\n\n`;
    md += `===================================================\n\n`;

    tasks.forEach((t) => {
      md += `### [${t.id}] ${t.title} (${(t.status || "todo").toUpperCase()})\n`;
      md += `- **Fase**: ${t.phase || "Fase Pengembangan"}\n`;
      md += `- **Prioritas**: ${t.priority}\n`;
      md += `- **File Target**: \`${(t.targetFiles || []).join("`, `")}\` \n`;
      md += `- **Dependensi**: ${(t.dependencies || []).length > 0 ? t.dependencies.join(", ") : "Tidak Ada"}\n\n`;
      md += `#### Instruksi Prompt AI Agent:\n\`\`\`\n${t.promptInstructions}\n\`\`\`\n\n`;
      md += `#### Langkah Verifikasi:\n${t.verificationSteps}\n\n`;
      md += `===================================================\n\n`;
    });

    return md;
  };

  const handleDownloadMdFile = () => {
    const content = buildBundledMarkdown();
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `AGENTS_${(session.input.title || "Proyek").toLowerCase().replace(/[^a-z0-9]/g, "_")}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyAllMd = () => {
    const content = buildBundledMarkdown();
    navigator.clipboard.writeText(content);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  // Ketiga kolom board dirender dari satu kerangka yang sama; hanya isi,
  // warna penanda, dan aksi di kaki kartunya yang berbeda per status.
  const columns = [
    {
      status: "todo" as const,
      label: "To do",
      dot: "bg-faint",
      tasks: tasks.filter((t) => !t.status || t.status === "todo"),
      emptyHint: "Semua task sudah dikerjakan.",
    },
    {
      status: "in_progress" as const,
      label: "In progress",
      dot: "bg-warn animate-pulse",
      tasks: tasks.filter((t) => t.status === "in_progress"),
      emptyHint: 'Klik "Mulai" pada task To do untuk memindahkannya ke sini.',
    },
    {
      status: "done" as const,
      label: "Done",
      dot: "bg-ok",
      tasks: tasks.filter((t) => t.status === "done"),
      emptyHint: "Task yang sudah diverifikasi AI Agent muncul di sini.",
    },
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Page heading */}
      <div className="max-w-2xl">
        <h2 className="text-xl font-semibold tracking-tight text-ink">Task untuk AI Agent</h2>
        <p className="text-muted mt-1.5 leading-relaxed">
          PRD dipecah jadi task atomik dengan file target, dependensi, prompt, dan langkah verifikasi. Salin satu task,
          atau unduh AGENTS.md untuk diberikan ke Cursor, Claude Code, atau Gemini.
        </p>
      </div>

      {/* Error Alert */}
      {errorMessage && (
        <div className="max-w-3xl p-4 bg-danger-soft border border-danger/30 text-danger-ink rounded-xl">
          <strong className="font-semibold">Error:</strong> {errorMessage}
        </div>
      )}

      {/* Generate Card if no tasks yet */}
      {tasks.length === 0 ? (
        <div className="card max-w-3xl p-10 text-center space-y-4">
          <div className="w-12 h-12 bg-ok-soft text-ok rounded-xl mx-auto flex items-center justify-center">
            <Bot className="w-6 h-6" />
          </div>
          <div className="max-w-md mx-auto space-y-1.5">
            <h3 className="font-semibold text-ink text-base">Bangun Kanban task board untuk AI Agent</h3>
            <p className="text-muted leading-relaxed">
              LLM memecah PRD dan arsitektur menjadi urutan task modular siap eksekusi dengan status To Do, In Progress,
              dan Done.
            </p>
          </div>
          <button onClick={handleGenerateTasks} disabled={loading} className="btn-primary mx-auto">
            {loading ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                Membangun task board...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate task board
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-5 animate-in fade-in duration-300">
          {/* Header Action Bar */}
          <div className="card p-5 flex flex-wrap items-start justify-between gap-5">
            <div className="min-w-0">
              <div className="flex items-center gap-1.5 text-ok text-xs font-medium mb-1.5">
                <CheckCircle2 className="w-3.5 h-3.5" /> {tasks.length} task siap dieksekusi
              </div>
              <h3 className="text-base font-semibold text-ink">Task board</h3>
              <p className="text-muted mt-1 max-w-xl leading-relaxed">
                Kelola status task di board di bawah, atau unduh AGENTS.md untuk dijalankan oleh AI Agent Anda.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-2 shrink-0">
              <button onClick={handleCopyAllMd} className="btn-ghost">
                {copiedAll ? <Check className="w-4 h-4 text-ok" /> : <Copy className="w-4 h-4" />}
                {copiedAll ? "Tersalin" : "Copy semua"}
              </button>

              <button onClick={handleDownloadMdFile} className="btn-primary">
                <Download className="w-4 h-4" />
                Download AGENTS.md
              </button>
            </div>
          </div>

          {/* View Switcher Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="inline-flex items-center gap-1 bg-subtle p-1 rounded-lg">
              {(
                [
                  { id: "kanban", label: "Kanban board", icon: Kanban },
                  { id: "list", label: "Daftar detail", icon: ListOrdered },
                ] as const
              ).map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setViewMode(id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
                    viewMode === id ? "bg-surface text-ink shadow-xs" : "text-muted hover:text-ink"
                  }`}
                >
                  <Icon className="w-3.5 h-3.5" />
                  {label}
                </button>
              ))}
            </div>

            <button onClick={handleGenerateTasks} disabled={loading} className="btn-outline text-xs">
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              Regenerate tasks
            </button>
          </div>

          {/* VIEW 1: KANBAN BOARD */}
          {viewMode === "kanban" && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
              {columns.map((column) => (
                <div key={column.status} className="bg-subtle rounded-xl p-3 space-y-2.5">
                  <div className="flex items-center gap-2 px-1.5 pb-2 border-b border-line text-xs font-semibold uppercase tracking-wider text-muted">
                    <span className={`w-2 h-2 rounded-full ${column.dot}`} />
                    {column.label}
                    <span className="text-faint">{column.tasks.length}</span>
                  </div>

                  <div className="space-y-2.5">
                    {column.tasks.map((task) => (
                      <div
                        key={task.id}
                        onClick={() => setSelectedTaskForModal(task)}
                        className="card p-3.5 cursor-pointer transition-colors hover:border-accent space-y-2"
                      >
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-[11px] font-mono font-semibold px-1.5 py-0.5 rounded bg-subtle text-muted">
                            {task.id}
                          </span>
                          <span
                            className={`text-[11px] font-semibold px-1.5 py-0.5 rounded ${
                              task.priority === "High" ? "bg-danger-soft text-danger-ink" : "bg-warn-soft text-warn-ink"
                            }`}
                          >
                            {task.priority}
                          </span>
                        </div>

                        <h5
                          className={`font-medium text-xs leading-snug ${
                            column.status === "done" ? "text-muted line-through" : "text-ink"
                          }`}
                        >
                          {task.title}
                        </h5>

                        {column.status !== "done" && (
                          <p className="text-xs text-faint line-clamp-2">{task.promptInstructions}</p>
                        )}

                        <div className="pt-2 border-t border-line flex items-center justify-between gap-2 text-xs">
                          {column.status === "todo" && (
                            <>
                              <span className="text-faint font-mono truncate">{task.targetFiles?.[0] || "—"}</span>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "in_progress");
                                }}
                                className="font-medium text-accent hover:brightness-110 flex items-center gap-1 shrink-0"
                              >
                                Mulai <ArrowRight className="w-3 h-3" />
                              </button>
                            </>
                          )}

                          {column.status === "in_progress" && (
                            <>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "todo");
                                }}
                                className="text-faint hover:text-ink"
                              >
                                Kembali
                              </button>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "done");
                                }}
                                className="font-medium text-ok hover:brightness-110 flex items-center gap-1"
                              >
                                Tandai selesai <Check className="w-3 h-3" />
                              </button>
                            </>
                          )}

                          {column.status === "done" && (
                            <>
                              <span className="text-ok flex items-center gap-1">
                                <Check className="w-3 h-3" /> Terverifikasi
                              </span>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "in_progress");
                                }}
                                className="text-faint hover:text-ink"
                              >
                                Buka kembali
                              </button>
                            </>
                          )}
                        </div>
                      </div>
                    ))}

                    {column.tasks.length === 0 && (
                      <p className="p-5 text-center text-xs text-faint rounded-lg border border-dashed border-line">
                        {column.emptyHint}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* VIEW 2: DETAILED LIST VIEW */}
          {viewMode === "list" && (
            <div className="max-w-5xl space-y-3">
              {tasks.map((task, idx) => {
                const isExpanded = expandedTasks[task.id] ?? true;
                const isCopied = copiedTaskId === task.id;

                return (
                  <div key={task.id || idx} className="card overflow-hidden">
                    <div
                      onClick={() => toggleExpand(task.id)}
                      className="px-4 py-3 bg-subtle border-b border-line flex flex-wrap items-center justify-between gap-3 cursor-pointer select-none"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <span className="px-1.5 py-0.5 rounded bg-surface text-muted font-mono font-medium text-[11px] shrink-0">
                          {task.id}
                        </span>

                        <div className="min-w-0">
                          <div className="flex flex-wrap items-baseline gap-x-2 text-xs text-faint">
                            <span>{task.phase || "Fase utama"}</span>
                            <span>&middot;</span>
                            <span className={task.priority === "High" ? "text-danger font-medium" : ""}>
                              Prioritas {task.priority}
                            </span>
                          </div>
                          <h5 className="font-medium text-ink mt-0.5 truncate">{task.title}</h5>
                        </div>
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleCopyTaskPrompt(task);
                          }}
                          className="btn-outline text-xs !py-1.5"
                        >
                          {isCopied ? <Check className="w-3.5 h-3.5 text-ok" /> : <Copy className="w-3.5 h-3.5" />}
                          {isCopied ? "Tersalin" : "Copy prompt"}
                        </button>

                        <span className="p-1.5 text-faint">
                          {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </span>
                      </div>
                    </div>

                    {isExpanded && (
                      <div className="p-5 space-y-4">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                          <div>
                            <span className="text-[11px] font-semibold text-faint uppercase tracking-wider block mb-1.5">
                              File target
                            </span>
                            <div className="flex flex-wrap gap-1">
                              {task.targetFiles?.map((f, fIdx) => (
                                <span
                                  key={fIdx}
                                  className="font-mono text-xs bg-subtle text-muted px-1.5 py-0.5 rounded"
                                >
                                  {f}
                                </span>
                              ))}
                            </div>
                          </div>

                          <div>
                            <span className="text-[11px] font-semibold text-faint uppercase tracking-wider block mb-1.5">
                              Dependensi
                            </span>
                            <div className="text-muted">
                              {task.dependencies && task.dependencies.length > 0 ? (
                                task.dependencies.join(", ")
                              ) : (
                                <span className="text-faint">Tidak ada dependensi</span>
                              )}
                            </div>
                          </div>
                        </div>

                        <div>
                          <span className="text-xs font-medium text-muted flex items-center gap-1.5 mb-1.5">
                            <Code2 className="w-3.5 h-3.5 text-accent" /> Instruksi prompt untuk AI Agent
                          </span>
                          <div className="bg-code text-code-ink font-mono text-xs leading-relaxed p-4 rounded-lg overflow-x-auto whitespace-pre-wrap select-all">
                            {task.promptInstructions}
                          </div>
                        </div>

                        <div className="p-3.5 bg-ok-soft rounded-lg text-ok-ink">
                          <strong className="font-medium mb-1 flex items-center gap-1.5">
                            <CheckCircle2 className="w-3.5 h-3.5" /> Langkah verifikasi
                          </strong>
                          <p className="text-xs leading-relaxed opacity-90">{task.verificationSteps}</p>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* TASK DETAIL MODAL */}
      {selectedTaskForModal && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="card max-w-2xl w-full max-h-[85vh] overflow-y-auto shadow-lg animate-in zoom-in-95 duration-150">
            <div className="sticky top-0 bg-surface flex items-start justify-between gap-4 border-b border-line px-6 py-4">
              <div className="min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-[11px] font-semibold px-1.5 py-0.5 rounded bg-subtle text-muted">
                    {selectedTaskForModal.id}
                  </span>
                  <span className="text-xs text-faint truncate">{selectedTaskForModal.phase}</span>
                </div>
                <h3 className="text-base font-semibold text-ink">{selectedTaskForModal.title}</h3>
              </div>
              <button
                onClick={() => setSelectedTaskForModal(null)}
                className="p-1.5 shrink-0 rounded-lg text-faint hover:text-ink hover:bg-subtle transition-colors"
                aria-label="Tutup"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-4">
              <div>
                <span className="field-label">Status pekerjaan</span>
                <div className="inline-flex items-center gap-1 bg-subtle p-1 rounded-lg">
                  {(
                    [
                      ["todo", "To do"],
                      ["in_progress", "In progress"],
                      ["done", "Done"],
                    ] as const
                  ).map(([status, label]) => {
                    const isActive =
                      selectedTaskForModal.status === status ||
                      (status === "todo" && !selectedTaskForModal.status);
                    return (
                      <button
                        key={status}
                        onClick={() => handleTaskStatusChange(selectedTaskForModal.id, status)}
                        className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                          isActive ? "bg-surface text-ink shadow-xs" : "text-muted hover:text-ink"
                        }`}
                      >
                        {label}
                      </button>
                    );
                  })}
                </div>
              </div>

              <div>
                <span className="field-label">File target</span>
                <div className="flex flex-wrap gap-1">
                  {selectedTaskForModal.targetFiles?.map((f, i) => (
                    <span key={i} className="font-mono text-xs bg-subtle text-muted px-2 py-1 rounded">
                      {f}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="field-label">Prompt instruksi untuk AI Agent</span>
                <div className="p-4 bg-code text-code-ink font-mono text-xs rounded-lg whitespace-pre-wrap leading-relaxed select-all overflow-x-auto">
                  {selectedTaskForModal.promptInstructions}
                </div>
              </div>

              <div className="p-4 bg-ok-soft rounded-lg text-ok-ink">
                <strong className="text-xs font-medium block mb-1">Langkah verifikasi</strong>
                <p className="text-xs opacity-90">{selectedTaskForModal.verificationSteps}</p>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-line">
              <button onClick={() => handleCopyTaskPrompt(selectedTaskForModal)} className="btn-primary">
                {copiedTaskId === selectedTaskForModal.id ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copiedTaskId === selectedTaskForModal.id ? "Tersalin" : "Copy task prompt"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
