import React, { useRef, useState } from "react";
import { ProjectSession, AgentTask } from "../types";
import confetti from "canvas-confetti";
import { generateTasks, isAbort } from "../lib/generate";
import { GenerationDialog } from "./GenerationDialog";
import {
  Bot,
  Sparkles,
  Download,
  Copy,
  Check,
  RefreshCw,
  Code2,
  CheckCircle2,
  ListOrdered,
  ChevronDown,
  ChevronUp,
  Kanban,
  ArrowRight,
  ArrowLeft,
  X,
} from "lucide-react";
import { useT } from "../lib/i18n";

interface Step3AgentTasksProps {
  session: ProjectSession;
  onUpdateSession: (updated: Partial<ProjectSession>) => void;
}

type TaskStatus = "todo" | "in_progress" | "done";

export const Step3AgentTasks: React.FC<Step3AgentTasksProps> = ({ session, onUpdateSession }) => {
  const { t, lang } = useT();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedTaskId, setCopiedTaskId] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);
  const [expandedTasks, setExpandedTasks] = useState<Record<string, boolean>>({});
  const [viewMode, setViewMode] = useState<"kanban" | "list">("kanban");
  const [selectedTaskForModal, setSelectedTaskForModal] = useState<AgentTask | null>(null);

  // Kartu dipindah dengan drag-and-drop HTML5 asli — tidak perlu pustaka untuk
  // tiga kolom. Tombol kecil di kaki kartu tetap ada: drag HTML5 tidak bekerja
  // di layar sentuh, dan tombol juga terjangkau lewat keyboard.
  const [draggingId, setDraggingId] = useState<string | null>(null);
  const [dropTarget, setDropTarget] = useState<TaskStatus | null>(null);
  const tasksAbort = useRef<AbortController | null>(null);

  const tasks = session.tasks || [];

  const handleGenerateTasks = async () => {
    setLoading(true);
    setErrorMessage(null);
    const controller = new AbortController();
    tasksAbort.current = controller;

    try {
      const generatedTasks = await generateTasks(session, lang, controller.signal);
      onUpdateSession({ tasks: generatedTasks });

      // Expand all by default
      const initialExpanded: Record<string, boolean> = {};
      generatedTasks.forEach((task) => (initialExpanded[task.id] = true));
      setExpandedTasks(initialExpanded);

      // Trigger celebratory confetti
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
      });
    } catch (err: any) {
      if (!isAbort(err)) {
        setErrorMessage(err.message || t("Something went wrong while generating the agent tasks."));
      }
    } finally {
      tasksAbort.current = null;
      setLoading(false);
    }
  };

  const handleTaskStatusChange = (taskId: string, newStatus: TaskStatus) => {
    const updated = tasks.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t));
    onUpdateSession({ tasks: updated });
    if (selectedTaskForModal && selectedTaskForModal.id === taskId) {
      setSelectedTaskForModal({ ...selectedTaskForModal, status: newStatus });
    }
  };

  const toggleExpand = (id: string) => {
    setExpandedTasks((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleCopyTaskPrompt = (task: AgentTask) => {
    // Isi bundel selalu Inggris: pembacanya adalah AI coding agent, bukan
    // pengguna, dan prompt agent lain di sekitarnya pun berbahasa Inggris.
    const text = `AI AGENT PROMPT [${task.id}] - ${task.title}\n` +
      `Target files: ${(task.targetFiles || []).join(", ")}\n` +
      `\nInstructions:\n${task.promptInstructions}\n` +
      `\nVerification steps:\n${task.verificationSteps}`;

    navigator.clipboard.writeText(text);
    setCopiedTaskId(task.id);
    setTimeout(() => setCopiedTaskId(null), 2000);
  };

  const buildBundledMarkdown = (): string => {
    const titleStr = session.input.title || session.title || "AI PROJECT";
    let md = `# AI AGENT EXECUTION TASKS: ${titleStr.toUpperCase()}\n\n`;
    md += `> Generated by The Architech on ${new Date().toLocaleDateString()}\n`;
    md += `> Target System: AI Coding Agent (Cursor, Antigravity Agent, Gemini, Claude Code)\n\n`;
    md += `## RULES FOR AI AGENT EXECUTION\n`;
    md += `1. Work through the tasks in ID order (TASK-01, TASK-02, ...).\n`;
    md += `2. Always read the target file before editing it, to avoid conflicts.\n`;
    md += `3. Run the verification at the end of each task before moving on.\n\n`;
    md += `===================================================\n\n`;

    // Bukan "t": nama itu sudah dipakai fungsi terjemahan di scope luar.
    tasks.forEach((task) => {
      md += `### [${task.id}] ${task.title} (${(task.status || "todo").toUpperCase()})\n`;
      md += `- **Phase**: ${task.phase || "Development"}\n`;
      md += `- **Priority**: ${task.priority}\n`;
      md += `- **Target files**: \`${(task.targetFiles || []).join("`, `")}\` \n`;
      md += `- **Dependencies**: ${(task.dependencies || []).length > 0 ? task.dependencies.join(", ") : "None"}\n\n`;
      md += `#### AI agent prompt:\n\`\`\`\n${task.promptInstructions}\n\`\`\`\n\n`;
      md += `#### Verification steps:\n${task.verificationSteps}\n\n`;
      md += `===================================================\n\n`;
    });

    return md;
  };

  const handleDownloadMdFile = () => {
    const content = buildBundledMarkdown();
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `AGENTS_${(session.input.title || "project").toLowerCase().replace(/[^a-z0-9]/g, "_")}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyAllMd = () => {
    const content = buildBundledMarkdown();
    navigator.clipboard.writeText(content);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  // Ketiga kolom board dirender dari satu kerangka yang sama; hanya isi,
  // warna penanda, dan aksi di kaki kartunya yang berbeda per status.
  const columns = [
    {
      status: "todo" as const,
      label: t("To do"),
      dot: "bg-faint",
      tasks: tasks.filter((t) => !t.status || t.status === "todo"),
      emptyHint: t("Every task has been dealt with."),
    },
    {
      status: "in_progress" as const,
      label: t("In progress"),
      dot: "bg-warn animate-pulse",
      tasks: tasks.filter((t) => t.status === "in_progress"),
      emptyHint: t('Hit "Start" on a To do task to move it here.'),
    },
    {
      status: "done" as const,
      label: t("Done"),
      dot: "bg-ok",
      tasks: tasks.filter((t) => t.status === "done"),
      emptyHint: t("Tasks the AI agent has verified show up here."),
    },
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Page heading */}
      <div className="max-w-2xl">
        <h2 className="text-xl font-semibold tracking-tight text-ink">{t("Tasks for the AI agent")}</h2>
        <p className="text-muted mt-1.5 leading-relaxed">
          {t(
            "The PRD is broken into atomic tasks with target files, dependencies, a prompt and verification steps. Copy a single task, or download AGENTS.md to hand to Cursor, Claude Code or Gemini."
          )}
        </p>
      </div>

      {/* Error Alert */}
      {errorMessage && (
        <div className="max-w-3xl p-4 bg-danger-soft border border-danger/30 text-danger-ink rounded-xl">
          <strong className="font-semibold">{t("Error")}:</strong> {errorMessage}
        </div>
      )}

      <GenerationDialog
        open={loading}
        title={t("Preparing the agent tasks")}
        label={t("Building the task board...")}
        expectedMs={45000}
        onCancel={() => tasksAbort.current?.abort()}
      />

      {/* Generate Card if no tasks yet */}
      {tasks.length === 0 ? (
        <div className="card max-w-3xl p-10 text-center space-y-4">
          <div className="w-12 h-12 bg-ok-soft text-ok rounded-xl mx-auto flex items-center justify-center">
            <Bot className="w-6 h-6" />
          </div>
          <div className="max-w-md mx-auto space-y-1.5">
            <h3 className="font-semibold text-ink text-base">{t("Build the Kanban task board for the AI agent")}</h3>
            <p className="text-muted leading-relaxed">
              {t("The LLM breaks the PRD and architecture into a sequence of modular, ready-to-run tasks with To do, In progress and Done states.")}
            </p>
          </div>
          <button onClick={handleGenerateTasks} disabled={loading} className="btn-primary mx-auto">
            {loading ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                {t("Building the task board...")}
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                {t("Generate task board")}
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-5 animate-in fade-in duration-300">
          {/* Header Action Bar */}
          <div className="card p-5 flex flex-wrap items-start justify-between gap-5">
            <div className="min-w-0">
              <div className="flex items-center gap-1.5 text-ok text-xs font-medium mb-1.5">
                <CheckCircle2 className="w-3.5 h-3.5" /> {t("{count} tasks ready to run", { count: tasks.length })}
              </div>
              <h3 className="text-base font-semibold text-ink">{t("Task board")}</h3>
              <p className="text-muted mt-1 max-w-xl leading-relaxed">
                {t("Move tasks between states on the board below, or download AGENTS.md for your AI agent to run.")}
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-2 shrink-0">
              <button onClick={handleCopyAllMd} className="btn-ghost">
                {copiedAll ? <Check className="w-4 h-4 text-ok" /> : <Copy className="w-4 h-4" />}
                {copiedAll ? t("Copied") : t("Copy all")}
              </button>

              <button onClick={handleDownloadMdFile} className="btn-primary">
                <Download className="w-4 h-4" />
                {t("Download AGENTS.md")}
              </button>
            </div>
          </div>

          {/* View Switcher Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="inline-flex items-center gap-1 bg-subtle p-1 rounded-lg">
              {(
                [
                  { id: "kanban", label: t("Kanban board"), icon: Kanban },
                  { id: "list", label: t("Detailed list"), icon: ListOrdered },
                ] as const
              ).map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setViewMode(id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
                    viewMode === id ? "bg-surface text-ink shadow-xs" : "text-muted hover:text-ink"
                  }`}
                >
                  <Icon className="w-3.5 h-3.5" />
                  {label}
                </button>
              ))}
            </div>

            <button onClick={handleGenerateTasks} disabled={loading} className="btn-outline text-xs">
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              {t("Regenerate tasks")}
            </button>
          </div>

          {/* VIEW 1: KANBAN BOARD */}
          {viewMode === "kanban" && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
              {columns.map((column) => (
                <div
                  key={column.status}
                  onDragOver={(e) => {
                    // Tanpa preventDefault, browser menolak jatuhan apa pun.
                    e.preventDefault();
                    e.dataTransfer.dropEffect = "move";
                    if (dropTarget !== column.status) setDropTarget(column.status);
                  }}
                  onDragLeave={(e) => {
                    // Pindah antar anak kolom ikut memicu dragleave; hanya yang
                    // benar-benar keluar dari kolom yang dihitung.
                    if (!e.currentTarget.contains(e.relatedTarget as Node)) {
                      setDropTarget((current) => (current === column.status ? null : current));
                    }
                  }}
                  onDrop={(e) => {
                    e.preventDefault();
                    const id = e.dataTransfer.getData("text/plain") || draggingId;
                    const task = tasks.find((item) => item.id === id);
                    if (task && (task.status || "todo") !== column.status) {
                      handleTaskStatusChange(id, column.status);
                    }
                    setDropTarget(null);
                    setDraggingId(null);
                  }}
                  className={`bg-subtle rounded-xl p-3 space-y-2.5 min-h-32 transition-colors ${
                    dropTarget === column.status ? "ring-2 ring-accent ring-inset" : ""
                  }`}
                >
                  <div className="flex items-center gap-2 px-1.5 pb-2 border-b border-line text-xs font-semibold uppercase tracking-wider text-muted">
                    <span className={`w-2 h-2 rounded-full ${column.dot}`} />
                    {column.label}
                    <span className="text-faint">{column.tasks.length}</span>
                  </div>

                  <div className="space-y-2.5">
                    {column.tasks.map((task) => (
                      <div
                        key={task.id}
                        draggable
                        onDragStart={(e) => {
                          e.dataTransfer.setData("text/plain", task.id);
                          e.dataTransfer.effectAllowed = "move";
                          setDraggingId(task.id);
                        }}
                        onDragEnd={() => {
                          setDraggingId(null);
                          setDropTarget(null);
                        }}
                        onClick={() => setSelectedTaskForModal(task)}
                        className={`card p-3.5 cursor-grab active:cursor-grabbing transition-colors hover:border-accent space-y-2 ${
                          draggingId === task.id ? "opacity-40" : ""
                        }`}
                      >
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-[11px] font-mono font-semibold px-1.5 py-0.5 rounded bg-subtle text-muted">
                            {task.id}
                          </span>
                          <span
                            className={`text-[11px] font-semibold px-1.5 py-0.5 rounded ${
                              task.priority === "High" ? "bg-danger-soft text-danger-ink" : "bg-warn-soft text-warn-ink"
                            }`}
                          >
                            {task.priority}
                          </span>
                        </div>

                        <h5
                          className={`font-medium text-xs leading-snug ${
                            column.status === "done" ? "text-muted line-through" : "text-ink"
                          }`}
                        >
                          {task.title}
                        </h5>

                        {column.status !== "done" && (
                          <p className="text-xs text-faint line-clamp-2">{task.promptInstructions}</p>
                        )}

                        <div className="pt-2 border-t border-line flex items-center justify-between gap-2 text-xs">
                          {column.status === "todo" && (
                            <>
                              <span className="text-faint font-mono truncate">{task.targetFiles?.[0] || "—"}</span>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "in_progress");
                                }}
                                className="font-medium text-accent hover:brightness-110 flex items-center gap-1 shrink-0"
                              >
                                {t("Start")} <ArrowRight className="w-3 h-3" />
                              </button>
                            </>
                          )}

                          {column.status === "in_progress" && (
                            <>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "todo");
                                }}
                                className="text-muted hover:text-ink flex items-center gap-1"
                              >
                                <ArrowLeft className="w-3 h-3" />
                                {t("Back")}
                              </button>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "done");
                                }}
                                className="font-medium text-ok hover:brightness-110 flex items-center gap-1"
                              >
                                {t("Mark done")} <Check className="w-3 h-3" />
                              </button>
                            </>
                          )}

                          {column.status === "done" && (
                            <>
                              <span className="text-ok flex items-center gap-1">
                                <Check className="w-3 h-3" /> {t("Verified")}
                              </span>
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleTaskStatusChange(task.id, "in_progress");
                                }}
                                className="text-muted hover:text-ink flex items-center gap-1"
                              >
                                <ArrowLeft className="w-3 h-3" />
                                {t("Reopen")}
                              </button>
                            </>
                          )}
                        </div>
                      </div>
                    ))}

                    {column.tasks.length === 0 && (
                      <p className="p-5 text-center text-xs text-faint rounded-lg border border-dashed border-line">
                        {column.emptyHint}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* VIEW 2: DETAILED LIST VIEW */}
          {viewMode === "list" && (
            <div className="max-w-5xl space-y-3">
              {tasks.map((task, idx) => {
                const isExpanded = expandedTasks[task.id] ?? true;
                const isCopied = copiedTaskId === task.id;

                return (
                  <div key={task.id || idx} className="card overflow-hidden">
                    <div
                      onClick={() => toggleExpand(task.id)}
                      className="px-4 py-3 bg-subtle border-b border-line flex flex-wrap items-center justify-between gap-3 cursor-pointer select-none"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <span className="px-1.5 py-0.5 rounded bg-surface text-muted font-mono font-medium text-[11px] shrink-0">
                          {task.id}
                        </span>

                        <div className="min-w-0">
                          <div className="flex flex-wrap items-baseline gap-x-2 text-xs text-faint">
                            <span>{task.phase || t("Main phase")}</span>
                            <span>&middot;</span>
                            <span className={task.priority === "High" ? "text-danger font-medium" : ""}>
                              {t("Priority {level}", { level: task.priority })}
                            </span>
                          </div>
                          <h5 className="font-medium text-ink mt-0.5 truncate">{task.title}</h5>
                        </div>
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleCopyTaskPrompt(task);
                          }}
                          className="btn-outline text-xs !py-1.5"
                        >
                          {isCopied ? <Check className="w-3.5 h-3.5 text-ok" /> : <Copy className="w-3.5 h-3.5" />}
                          {isCopied ? t("Copied") : t("Copy prompt")}
                        </button>

                        <span className="p-1.5 text-faint">
                          {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </span>
                      </div>
                    </div>

                    {isExpanded && (
                      <div className="p-5 space-y-4">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                          <div>
                            <span className="text-[11px] font-semibold text-faint uppercase tracking-wider block mb-1.5">
                              {t("Target files")}
                            </span>
                            <div className="flex flex-wrap gap-1">
                              {task.targetFiles?.map((f, fIdx) => (
                                <span
                                  key={fIdx}
                                  className="font-mono text-xs bg-subtle text-muted px-1.5 py-0.5 rounded"
                                >
                                  {f}
                                </span>
                              ))}
                            </div>
                          </div>

                          <div>
                            <span className="text-[11px] font-semibold text-faint uppercase tracking-wider block mb-1.5">
                              {t("Dependencies")}
                            </span>
                            <div className="text-muted">
                              {task.dependencies && task.dependencies.length > 0 ? (
                                task.dependencies.join(", ")
                              ) : (
                                <span className="text-faint">{t("No dependencies")}</span>
                              )}
                            </div>
                          </div>
                        </div>

                        <div>
                          <span className="text-xs font-medium text-muted flex items-center gap-1.5 mb-1.5">
                            <Code2 className="w-3.5 h-3.5 text-accent" /> {t("Prompt instructions for the AI agent")}
                          </span>
                          <div className="bg-code text-code-ink font-mono text-xs leading-relaxed p-4 rounded-lg overflow-x-auto whitespace-pre-wrap select-all">
                            {task.promptInstructions}
                          </div>
                        </div>

                        <div className="p-3.5 bg-ok-soft rounded-lg text-ok-ink">
                          <strong className="font-medium mb-1 flex items-center gap-1.5">
                            <CheckCircle2 className="w-3.5 h-3.5" /> {t("Verification steps")}
                          </strong>
                          <p className="text-xs leading-relaxed opacity-90">{task.verificationSteps}</p>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* TASK DETAIL MODAL */}
      {selectedTaskForModal && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="card max-w-2xl w-full max-h-[85vh] overflow-y-auto shadow-lg animate-in zoom-in-95 duration-150">
            <div className="sticky top-0 bg-surface flex items-start justify-between gap-4 border-b border-line px-6 py-4">
              <div className="min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-[11px] font-semibold px-1.5 py-0.5 rounded bg-subtle text-muted">
                    {selectedTaskForModal.id}
                  </span>
                  <span className="text-xs text-faint truncate">{selectedTaskForModal.phase}</span>
                </div>
                <h3 className="text-base font-semibold text-ink">{selectedTaskForModal.title}</h3>
              </div>
              <button
                onClick={() => setSelectedTaskForModal(null)}
                className="p-1.5 shrink-0 rounded-lg text-faint hover:text-ink hover:bg-subtle transition-colors"
                aria-label={t("Close")}
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-4">
              <div>
                <span className="field-label">{t("Work status")}</span>
                <div className="inline-flex items-center gap-1 bg-subtle p-1 rounded-lg">
                  {(
                    [
                      ["todo", t("To do")],
                      ["in_progress", t("In progress")],
                      ["done", t("Done")],
                    ] as const
                  ).map(([status, label]) => {
                    const isActive =
                      selectedTaskForModal.status === status ||
                      (status === "todo" && !selectedTaskForModal.status);
                    return (
                      <button
                        key={status}
                        onClick={() => handleTaskStatusChange(selectedTaskForModal.id, status)}
                        className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                          isActive ? "bg-surface text-ink shadow-xs" : "text-muted hover:text-ink"
                        }`}
                      >
                        {label}
                      </button>
                    );
                  })}
                </div>
              </div>

              <div>
                <span className="field-label">{t("Target files")}</span>
                <div className="flex flex-wrap gap-1">
                  {selectedTaskForModal.targetFiles?.map((f, i) => (
                    <span key={i} className="font-mono text-xs bg-subtle text-muted px-2 py-1 rounded">
                      {f}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="field-label">{t("Prompt instructions for the AI agent")}</span>
                <div className="p-4 bg-code text-code-ink font-mono text-xs rounded-lg whitespace-pre-wrap leading-relaxed select-all overflow-x-auto">
                  {selectedTaskForModal.promptInstructions}
                </div>
              </div>

              <div className="p-4 bg-ok-soft rounded-lg text-ok-ink">
                <strong className="text-xs font-medium block mb-1">{t("Verification steps")}</strong>
                <p className="text-xs opacity-90">{selectedTaskForModal.verificationSteps}</p>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-line">
              <button onClick={() => handleCopyTaskPrompt(selectedTaskForModal)} className="btn-primary">
                {copiedTaskId === selectedTaskForModal.id ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copiedTaskId === selectedTaskForModal.id ? t("Copied") : t("Copy task prompt")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
